sudo: false
language: node_js
node_js:
  - "8"
  - "10"
env:
  - EGG_VERSION=1
  - EGG_VERSION=2
before_install:
  - npm install npminstall -g
install:
  - sed -i.bak '/"egg":/d' package.json
  - npminstall -d
script:
  - eval "npminstall -d egg@$EGG_VERSION"
  - npm run ci
after_script:
  - npminstall codecov && codecov
