name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Job:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-test-parallel.yml@test-parallel
    with:
      os: 'ubuntu-latest, macos-latest, windows-latest'
      version: '18.19.0, 18, 20, 22, 23'
      parallel: 4
      action_ref: 'test-parallel'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
