name: CI

on:
  push:
    branches: [ master, 6.x, 5.x ]

  pull_request:
    branches: [ master, 6.x, 5.x ]

  workflow_dispatch: {}

jobs:
  Job:
    name: Node.js
    uses: artusjs/github-actions/.github/workflows/node-test.yml@v1
    with:
      os: 'ubuntu-latest, macos-latest, windows-latest'
      version: '16, 18, 19'
